[package]
name = "vee"
version = "0.1.0"
authors = ["James Robinson <robioson@pm.me>"]
edition = "2021"

[dependencies]
nanomsg = { version = "0.7.2", features = ["bundled"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
